---
# tasks file for ec2-cloudwatch-logs
- include: install.yml
  become: true
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
- include: cleanup.yml
  become: true
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
